name: Weekly database update

on:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: execute py script # run main.py
        run: test.py
        
      - uses: actions/checkout@v3
      - name: Commit 
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -am "test"

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: test 
          
